package algebra

import "github.com/cronokirby/saferith"

// AbstractGroupoid defines methods needed for S to be considered as a Groupoid.
// We assume the Groupoid is right associative.
// Groupoid/Magma is a set equipped with a binary operator that is closed under
// said operator.
type AbstractGroupoid[S Structure, E Element] interface {
	// Groupoid is a structured set.
	AbstractStructuredSet[S, E]
}

// AbstractGroupoidElement defines methods for E to be considered an element of S
// where S is a Groupoid.
// Groupoid/Magma is a set equipped with a binary operator that is closed under
// said operator.
type AbstractGroupoidElement[S Structure, E Element] interface {
	// Groupoid Element is an element of a structured set.
	AbstractStructuredSetElement[S, E]

	// Operate uses the underlying binary operator to map this element and `rhs` to another element of type E.
	Operate(rhs E) E

	// OperateIteratively calls x.Operate(x).Operate(x)...Operate(x), `n - 1` many times (aka Exp).
	// It is equivalent to defining an operator with the higher index in the hyperoperator sequence if `n` == lhs.
	OperateIteratively(n *saferith.Nat) E

	// Order is the size the structure of the same type S generated by this element.
	Order() *saferith.Modulus
}

// AdditiveGroupoidTrait defines additional methods for the groupoid S if the operator is some form of addition.
type AdditiveGroupoidTrait[S Structure, E Element] interface {
	// Add accepts elements x and a the list of elements ys and adds returns sum(x, ys). We assume S with its
	// addition operator is right associative.
	Add(x E, ys ...E) E
}

// AdditiveGroupoidElementTrait defines additional methods for the elements of type E of the groupoid S, if
// the operator is some form of addition.
type AdditiveGroupoidElementTrait[S Structure, E Element] interface {
	// Add adds this element to the input element and returns an element of type E.
	Add(rhs E) E
	// ApplyAdd calls this.Add(x).Add(x)...Add(x), `n` many times.
	ApplyAdd(x E, n *saferith.Nat) E
	// Double returns the value of x.Add(x)
	Double() E
	// Triple returns the value of x.Add(x).Add(x)
	Triple() E
}

// MultiplicativeGroupoidTrait defines additional methods for the elements of type E of the groupoid S, if
// the operator is some form of multiplication.
type MultiplicativeGroupoidTrait[S Structure, E Element] interface {
	// Multiply accepts elements x and a the list of elements ys and adds returns product(x, ys). We assume S with its
	// multiplication operator is right associative.
	Multiply(x E, ys ...E) E
}

// MultiplicativeGroupoidElementTrait defines additional methods for the elements of type E of the groupoid S, if
// the operator is some form of multiplication.
type MultiplicativeGroupoidElementTrait[S Structure, E Element] interface {
	// Mul multiplies this element to the input element and returns an element of type E.
	Mul(rhs E) E
	// ApplyMul calls this.Mul(x).Mul(x)...Mul(x), `n` many times.
	ApplyMul(x E, n *saferith.Nat) E
	// Square returns the values of x.Mul(x)
	Square() E
	// Cube returns the values of x.Mul(x).Mul(x)
	Cube() E
}
