version: "2"
run:
  build-tags:
    - nobignum
    - purego
  tests: true

formatters:
  enable:
    # Gci control golang package import order and make it always deterministic.
    - gci
    # Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification.
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bronlabs)
        - blank
        - dot
      custom-order: true
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - gen
      - testutils
      - thirdparty
      - third_party$
      - builtin$
      - examples$
linters:
  default: none
  enable:
    # Check for pass []any as any in variadic func(...any).
    - asasalint
    # Simple linter to check that your code does not contain non-ASCII identifiers
    - asciicheck
    # Checks for dangerous unicode character sequences.
    - bidichk
    # Copyloopvar is a linter detects places where loop variables are copied.
    - copyloopvar
    # Go linter that checks if package imports are in a list of acceptable
    # packages.
    - depguard
    # Checks assignments with too many blank identifiers (e.g. x, , , _, := f())
    - dogsled
    # Tool for code clone detection
    - dupl
    # Checks for duplicate words in the source code.
    - dupword
    # Embedded types should be at the top of the field list of a struct, and there must be an empty line separating embedded fields from regular fields.
    - embeddedstructfieldcheck
    # Golang linter to check the errors handling expressions
    - err113
    # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
    - errcheck
    # # TODO: add when sentinel errors are used
    # # Checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error.
    # - errname
    # errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13.
    - errorlint
    # check exhaustiveness of enum switch statements
    - exhaustive
    # Checks if all structure fields are initialized.
    - exhaustruct
    # Detects functions from golang.org/x/exp/ that can be replaced by std functions.
    - exptostd
    # Forbids identifiers
    - forbidigo
    # finds forced type assertions
    - forcetypeassert
    # Checks that go compiler directive comments (//go:) are valid.
    - gocheckcompilerdirectives
    # Checks that no init functions are present in Go code
    - gochecknoinits
    # Run exhaustiveness checks on Go "sum types".
    - gochecksumtype
    # Finds repeated strings that could be replaced by a constant
    - goconst
    # Provides many diagnostics that check for bugs, performance and style issues. Extensible without recompilation through dynamic rules. Dynamic rules are written declaratively with AST patterns, filters, report message and optional suggestion.
    - gocritic
    # Check if comments end in a period
    - godot
    # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod.
    - gomoddirectives
    # Checks that printf-like functions are named with f at the end
    - goprintffuncname
    # Inspects source code for security problems
    - gosec
    # Report certain i18n/l10n anti-patterns in your Go codebase.
    - gosmopolitan
    # Reports wrong mirror patterns of bytes/strings usage.
    - mirror
    # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - govet
    # # Checks that your code uses short syntax for if-statements whenever possible
    # # TODO: enable this when we have an alternative. It's currently flaky as
    # # well as unmainted
    # - ifshort
    # Enforces consistent import aliases
    - importas
    # Reports interfaces with unnamed method parameters.
    - inamedparam
    # # Intrange is a linter to find places where for loops could make use of an integer range.
    # TODO: Enable this when it doesn't panic.
    # - intrange
    # Detects when assignments to existing variables are not used
    - ineffassign
    # Finds slice declarations with non-zero initial length
    - makezero
    # Finds commonly misspelled English words in comments
    - misspell
    # Finds naked returns in functions greater than a specified function length
    - nakedret
    # Finds the code that returns nil even if it checks that the error is not nil.
    - nilerr
    # Reports ill-formed or insufficient nolint directives
    - nolintlint
    # Checks that there is no simultaneous return of nil error and an invalid value.
    - nilnil
    # Paralleltest detects missing usage of t.Parallel() method in your Go test.
    - paralleltest
    # Finds slice declarations that could potentially be preallocated
    - prealloc
    # find code that shadows one of Go's predeclared identifiers
    - predeclared
    # Check Prometheus metrics naming via promlint.
    - promlinter
    # Check that struct tags are well aligned.
    - tagalign
    # Checks the struct tags.
    - tagliatelle
    # Linter checks if examples are testable (have an expected output).
    - testableexamples
    # Checks usage of github.com/stretchr/testify.
    - testifylint
    # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint.
    - revive
    # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - staticcheck
    # linter that makes you use a separate _test package
    - testpackage
    # thelper detects golang test helpers without t.Helper() call and checks the consistency of test helpers
    - thelper
    # tparallel detects inappropriate usage of t.Parallel() method in your Go test codes
    - tparallel
    # Remove unnecessary type conversions
    - unconvert
    # Reports unused function parameters
    - unparam
    # A linter that detect the possibility to use variables/constants from the Go standard library.
    - usestdlibvars
    # Checks Go code for unused constants, variables, functions and types
    - unused
    # wastedassign finds wasted assignment statements.
    - wastedassign
    # Tool for detection of leading and trailing whitespace
    - whitespace
    # Checks that errors returned from external packages are wrapped
    - wrapcheck
    # Detects the wrong usage of zerolog that a user forgets to dispatch with Send or Msg.
    - zerologlint

  settings:
    asasalint:
      # To specify a set of function names to exclude.
      # The values are merged with the builtin exclusions.
      # The builtin exclusions can be disabled by setting `use-builtin-exclusions` to `false`.
      # Default: ["^(fmt|log|logger|t|)\.(Print|Fprint|Sprint|Fatal|Panic|Error|Warn|Warning|Info|Debug|Log)(|f|ln)$"]
      exclude:
        - \.Wrapf
      # To enable/disable the asasalint builtin exclusions of function names.
      # See the default value of `exclude` to get the builtin exclusions.
      use-builtin-exclusions: false
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Use custom error types from the errs package
    dogsled:
      max-blank-identifiers: 3
    dupl:
      threshold: 175
    dupword:
      keywords:
        - the
        - and
        - a
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - encoding/json.Marshal
        - encoding/json.MarshalIndent
    errchkjson:
      check-error-free-encoding: true
      report-no-exported: false
    errorlint:
      errorf: true
      errorf-multi: false
      asserts: true
      comparison: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: false
    forbidigo:
      forbid:
        - pattern: fmt\.Print.*
        - pattern: fmt\.Println.*
        - pattern: fmt\.Errorf.*
        - pattern: assert\.*
        - pattern: pubkey
        - pattern: Pubkey
        - pattern: PubKey
        - pattern: privkey
        - pattern: Privkey
    gochecksumtype:
      default-signifies-exhaustive: false
      include-shared-interfaces: false
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disable-all: true
      enabled-checks:
        - argOrder
        - badCall
        - badCond
        - badLock
        - badRegexp
        - badSorting
        - builtinShadowDecl
        - caseOrder
        - codegenComment
        - deferInLoop
        - deprecatedComment
        - dupArg
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - dynamicFmtString
        - emptyDecl
        - evalOrder
        - exitAfterDefer
        - externalErrorReassign
        - filepathJoin
        - flagDeref
        - flagName
        - mapKey
        - nilValReturn
        - offBy1
        - regexpPattern
        - returnAfterHttpError
        - sloppyReassign
        - sloppyTypeAssert
        - sortSlice
        - sprintfQuotedString
        - sqlQuery
        - syncMapLoadAndDelete
        - truncateCmp
        - uncheckedInlineErr
        - unnecessaryDefer
        - weakCond
        - assignOp
        - boolExprSimplify
        - builtinShadow
        - commentFormatting
        - commentedOutImport
        - defaultCaseOrder
        - deferUnlambda
        - docStub
        - dupImport
        - elseif
        - emptyFallthrough
        - emptyStringTest
        - exposedSyncMutex
        - hexLiteral
        - httpNoBody
        - ifElseChain
        - importShadow
        - initClause
        - methodExprCall
        - nestingReduce
        - newDeref
        - octalLiteral
        - paramTypeCombine
        - preferFilepathJoin
        - ptrToRefParam
        - redundantSprint
        - regexpMust
        - regexpSimplify
        - ruleguard
        - singleCaseSwitch
        - sloppyLen
        - stringConcatSimplify
        - stringsCompare
        - switchTrue
        - timeExprSimplify
        - todoCommentWithoutDetail
        - tooManyResultsChecker
        - typeAssertChain
        - typeDefFirst
        - typeSwitchVar
        - typeUnparen
        - underef
        - unlabelStmt
        - unlambda
        - unnamedResult
        - unnecessaryBlock
        - unslice
        - valSwap
        - whyNoLint
        - wrapperFunc
        - yodaStyleExpr
        - appendCombine
        - equalFold
        - hugeParam
        - indexAlloc
        - preferDecodeRune
        - preferFprint
        - preferStringWriter
        - preferWriteByte
        - rangeExprCopy
        - rangeValCopy
        - sliceClear
        - stringXbytes
      settings:
        hugeParam:
          sizeThreshold: 80
        nestingReduce:
          bodyWidth: 5
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        rangeValCopy:
          sizeThreshold: 128
          skipTestFuncs: true
        truncateCmp:
          skipArchDependent: true
        underef:
          skipRecvDeref: false
    godot:
      scope: toplevel
      exclude:
        - ^ [=-_]+$
        - ^ [A-Za-z-_]+$
        - ^ [A-Za-z-_]+ [A-Za-z-_]+$
        - '[TODO|FIXME]:'
        - '[:]+'
      capital: false
    gomoddirectives:
      replace-local: false
      exclude-forbidden: false
      retract-allow-no-explanation: false
    gosec:
      excludes:
        - G115
      severity: low
      confidence: low
      config:
        G101:
          entropy_threshold: "80.0"
          ignore_entropy: false
          pattern: (?i)example
          per_char_threshold: "3.0"
          truncate: "32"
        G104:
          fmt:
            - Fscanf
        G111:
          pattern: custom\.Dir\(\)
        G301: "0750"
        G302: "0600"
        G306: "0600"
        global:
          '#nosec': '#my-custom-nosec'
          audit: true
          nosec: true
          show-ignored: true
      concurrency: 12
    gosmopolitan:
      allow-time-local: false
      watch-for-scripts:
        - Devanagari
        - Han
        - Hangul
        - Hiragana
        - Katakana
    govet:
      disable:
        - fieldalignment
      enable-all: true
    importas:
      alias:
        - pkg: crypto/rand
          alias: crand
        - pkg: filippo.io/edwards25519
          alias: filippo
      no-unaliased: true
    misspell:
      locale: UK
      extra-words:
        - typo: quorom
          correction: quorum
        - typo: sharign
          correction: sharing
    paralleltest:
      ignore-missing: false
      ignore-missing-subtests: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    predeclared:
      qualified-name: true
    revive:
      rules:
        - name: context-keys-type
        - name: time-equal
        - name: time-naming
        - name: var-declaration
        - name: unexported-return
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: empty-block
        - name: deep-exit
        - name: superfluous-else
        - name: get-return
        - name: modifies-parameter
        - name: optimize-operands-order
        - name: string-format
        - name: confusing-results
        - name: datarace
        - name: unreachable-code
        - name: unnecessary-stmt
        - name: struct-tag
        - name: atomic
        - name: modifies-value-receiver
        - name: constant-logical-expr
        - name: bool-literal-in-expr
        - name: redefines-builtin-id
        - name: range-val-in-closure
        - name: range-val-address
        - name: waitgroup-by-value
        - name: call-to-gc
        - name: duplicated-imports
        - name: import-shadowing
        - name: bare-return
        - name: unused-receiver
        - name: string-of-int
        - name: early-return
        - name: unconditional-recursion
        - name: identical-branches
        - name: defer
          arguments:
            - - call-chain
              - method-call
              - recover
              - return
    staticcheck:
      checks:
        - all
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          env: upperSnake
          envconfig: upperSnake
          json: camel
          mapstructure: kebab
          xml: camel
          yaml: camel
        use-field-name: false
    testifylint:
      enable-all: true
      disable:
        - compares
      suite-extra-assert-call:
        mode: require
    whitespace:
      multi-if: true
      multi-func: false
    wrapcheck:
      ignore-sigs:
        - errs.
      ignore-package-globs:
        - google.golang.org/grpc/status
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - asasalint
        path: (.+)_test\.go
    paths:
      - gen
      - testutils
      - thirdparty
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  fix: false