// Code generated by krypton-primitives. DO NOT EDIT.

package impl

import (
	"encoding/hex"
	"io"
	"math/big"
	"slices"
)

const (
	FqLimbs     = 4
	FqSatLimbs  = FqLimbs + 1
	FqBits      = 256
	FqBytes     = 8 * (((FqBits - 1) / 64) + 1)
	FqWideBytes = 2 * FqBytes
	FqDivSteps  = ((49 * FqBits) + 57) / 17
	FqE         = 4
)

var (
	FqProgenitorExp = [...]byte{0x2a, 0x19, 0xe3, 0x17, 0x56, 0xce, 0x9d, 0x27, 0xf4, 0xbc, 0x38, 0x6d, 0xd5, 0x37, 0xe7, 0xfd, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x07, 0x00, 0x00, 0x00, 0xf8, 0xff, 0xff, 0xff, 0x07}
	FqModulus       = [...]byte{0x51, 0x25, 0x63, 0xfc, 0xc2, 0xca, 0xb9, 0xf3, 0x84, 0x9e, 0x17, 0xa7, 0xad, 0xfa, 0xe6, 0xbc, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff}
	FqRootOfUnity   Fq
)

func init() {
	FqRootOfUnity.MustSetHex("ffc97f062a770992ba807ace842a3dfc1546cad004378daf0592d7fbb41e6602")
}

type Fq struct {
	fiatFqMontgomeryDomainFieldElement
}

func (f *Fq) Set(v *Fq) {
	*f = *v
}

func (f *Fq) SetZero() {
	*f = Fq{}
}

func (f *Fq) SetOne() {
	fiatFqSetOne(&f.fiatFqMontgomeryDomainFieldElement)
}

func (f *Fq) SetUint64(v uint64) {
	limbs := [FqLimbs]uint64{v}
	f.SetLimbs(limbs[:])
}

func (f *Fq) SetLimbs(data []uint64) (ok uint64) {
	fiatFqToMontgomery(&f.fiatFqMontgomeryDomainFieldElement, (*fiatFqNonMontgomeryDomainFieldElement)(data))
	return 1
}

func (f *Fq) SetBytes(data []byte) (ok uint64) {
	if len(data) != FqBytes {
		return 0
	}

	var nonMonty fiatFqNonMontgomeryDomainFieldElement
	fiatFqFromBytes((*[FqLimbs]uint64)(&nonMonty), (*[FqBytes]uint8)(data))
	fiatFqToMontgomery(&f.fiatFqMontgomeryDomainFieldElement, &nonMonty)
	return 1
}

func (f *Fq) SetBytesWide(data []byte) (ok uint64) {
	if len(data) > FqWideBytes {
		return 0
	}

	var wideData [FqWideBytes]uint8
	copy(wideData[:], data)

	var d1, d0 [FqLimbs]uint64
	fiatFqFromBytes(&d0, (*[FqBytes]uint8)(wideData[:FqBytes]))
	fiatFqFromBytes(&d1, (*[FqBytes]uint8)(wideData[FqBytes:]))

	// d0*r2 + d1*r3
	fiatFqToMontgomery((*fiatFqMontgomeryDomainFieldElement)(&d0), (*fiatFqNonMontgomeryDomainFieldElement)(&d0))
	fiatFqToMontgomery((*fiatFqMontgomeryDomainFieldElement)(&d1), (*fiatFqNonMontgomeryDomainFieldElement)(&d1))
	fiatFqToMontgomery((*fiatFqMontgomeryDomainFieldElement)(&d1), (*fiatFqNonMontgomeryDomainFieldElement)(&d1))
	fiatFqAdd(&f.fiatFqMontgomeryDomainFieldElement, (*fiatFqMontgomeryDomainFieldElement)(&d0), (*fiatFqMontgomeryDomainFieldElement)(&d1))
	return 1
}

func (f *Fq) SetUniformBytes(componentsData ...[]byte) (ok uint64) {
	if len(componentsData) != 1 {
		return 0
	}

	return f.SetBytesWide(componentsData[0])
}

func (f *Fq) SetRandom(prng io.Reader) (ok uint64) {
	var uniformBytes [(FqBits + 128 + 7) / 8]byte
	_, err := io.ReadFull(prng, uniformBytes[:])
	if err != nil {
		return 0
	}
	return f.SetUniformBytes(uniformBytes[:])
}

func (f *Fq) Select(choice uint64, z, nz *Fq) {
	fiatFqSelectznz((*[FqLimbs]uint64)(&f.fiatFqMontgomeryDomainFieldElement),fiatFqUint1(choice), (*[FqLimbs]uint64)(&z.fiatFqMontgomeryDomainFieldElement), (*[FqLimbs]uint64)(&nz.fiatFqMontgomeryDomainFieldElement))
}

func (f *Fq) Add(lhs, rhs *Fq) {
	fiatFqAdd(&f.fiatFqMontgomeryDomainFieldElement, &lhs.fiatFqMontgomeryDomainFieldElement, &rhs.fiatFqMontgomeryDomainFieldElement)
}

func (f *Fq) Sub(lhs, rhs *Fq) {
	fiatFqSub(&f.fiatFqMontgomeryDomainFieldElement, &lhs.fiatFqMontgomeryDomainFieldElement, &rhs.fiatFqMontgomeryDomainFieldElement)
}

func (f *Fq) Neg(v *Fq) {
	fiatFqOpp(&f.fiatFqMontgomeryDomainFieldElement, &v.fiatFqMontgomeryDomainFieldElement)
}

func (f *Fq) Mul(lhs, rhs *Fq) {
	fiatFqMul(&f.fiatFqMontgomeryDomainFieldElement, &lhs.fiatFqMontgomeryDomainFieldElement, &rhs.fiatFqMontgomeryDomainFieldElement)
}

func (f *Fq) Square(v *Fq) {
	fiatFqSquare(&f.fiatFqMontgomeryDomainFieldElement, &v.fiatFqMontgomeryDomainFieldElement)
}

func (f *Fq) Inv(a *Fq) (ok uint64) {
	var precomp, h, v, r, out4, out5 [FqLimbs]uint64
	var ff, g, out2, out3 [FqSatLimbs]uint64
	var out1, inverted uint64

	d := uint64(1)
	fiatFqDivstepPrecomp(&precomp)
	fiatFqFromMontgomery((*fiatFqNonMontgomeryDomainFieldElement)(g[:FqLimbs]), &a.fiatFqMontgomeryDomainFieldElement)
	fiatFqMsat(&ff)
	fiatFqSetOne((*fiatFqMontgomeryDomainFieldElement)(&r))

	for i := 0; i < FqDivSteps-(FqDivSteps%2); i += 2 {
		fiatFqDivstep(&out1, &out2, &out3, &out4, &out5, d, &ff, &g, &v, &r)
		fiatFqDivstep(&d, &ff, &g, &v, &r, out1, &out2, &out3, &out4, &out5)
	}
	if (FqDivSteps % 2) != 0 { // compile time if - always true
		fiatFqDivstep(&out1, &out2, &out3, &out4, &out5, d, &ff, &g, &v, &r)
		v = out4
		ff = out2
	}

	fiatFqOpp((*fiatFqMontgomeryDomainFieldElement)(&h), (*fiatFqMontgomeryDomainFieldElement)(&v))
	fiatFqSelectznz(&v, fiatFqUint1(ff[FqLimbs]>>63), &v, &h)
	fiatFqMul(&f.fiatFqMontgomeryDomainFieldElement, (*fiatFqMontgomeryDomainFieldElement)(&v), (*fiatFqMontgomeryDomainFieldElement)(&precomp))
	fiatFqNonzero(&inverted, (*[FqLimbs]uint64)(&f.fiatFqMontgomeryDomainFieldElement))

	return (inverted | -inverted) >> 63
}

func (f *Fq) Div(lhs, rhs *Fq) (ok uint64) {
	var rhsInv Fq
	ok = rhsInv.Inv(rhs)
	f.Mul(lhs, &rhsInv)
	return ok
}

func (f *Fq) Sqrt(x *Fq) (ok uint64) {
	return sqrt(f, x, &FqRootOfUnity, FqE, FqProgenitorExp[:])
}

func (f *Fq) IsNonZero() uint64 {
	// montgomery form might not be "fully reduced"
	var nonMonty fiatFqNonMontgomeryDomainFieldElement
	fiatFqFromMontgomery(&nonMonty, &f.fiatFqMontgomeryDomainFieldElement)

	var nonZero uint64
	fiatFqNonzero(&nonZero, (*[FqLimbs]uint64)(&nonMonty))
	return (nonZero | -nonZero) >> 63
}

func (f *Fq) IsZero() uint64 {
	return f.IsNonZero() ^ 1
}

func (f *Fq) IsOne() uint64 {
	var one Fq
	one.SetOne()
	return f.Equals(&one)
}

func (f *Fq) Equals(v *Fq) uint64 {
	var diff Fq
	diff.Sub(f, v)
	return diff.IsZero()
}

func (f *Fq) ComponentsBytes() [][]byte {
	return [][]byte{f.Bytes()}
}

func (f *Fq) Bytes() []byte {
	var nonMonty fiatFqNonMontgomeryDomainFieldElement
	fiatFqFromMontgomery(&nonMonty, &f.fiatFqMontgomeryDomainFieldElement)
	var data [FqBytes]byte
	fiatFqToBytes(&data, (*[FqLimbs]uint64)(&nonMonty))
	return data[:]

}

func (f *Fq) Limbs() []uint64 {
	var nonMonty fiatFqNonMontgomeryDomainFieldElement
	fiatFqFromMontgomery(&nonMonty, &f.fiatFqMontgomeryDomainFieldElement)
	return nonMonty[:]
}

func (f *Fq) MustSetHex(v string) {
	data, err := hex.DecodeString(v)
	if err != nil {
		panic(err)
	}
	slices.Reverse(data)
	ok := f.SetBytes(data)
	if ok != 1 {
		panic("invalid data")
	}
}

func (f *Fq) Hex() string {
	data := f.Bytes()
	slices.Reverse(data)
	return hex.EncodeToString(data)
}

func (f *Fq) Degree() uint64 {
	return 1
}

func (f *Fq) String() string {
	fBytes := f.Bytes()
	slices.Reverse(fBytes)
	fBi := new(big.Int).SetBytes(fBytes)
	return fBi.String()
}

func (f *Fq) GoString() string {
	fBytes := f.Bytes()
	slices.Reverse(fBytes)
	return "0x" + hex.EncodeToString(f.Bytes())
}
