// Code generated by bron-crypto. DO NOT EDIT.

package base

// Derived constants from the base security parameters in constants.go
const (
	// Computational security derived values
	ComputationalSecurityLog2Ceil  = 7
	ComputationalSecurityPow2Ceil  = 1 << ComputationalSecurityLog2Ceil
	ComputationalSecurityBytesCeil = 16 // ceil(ComputationalSecurityBits/8)

	// Statistical security derived values
	StatisticalSecurityLog2Ceil  = 7
	StatisticalSecurityPower2Ceil  = 1 << StatisticalSecurityLog2Ceil
	StatisticalSecurityBytesCeil = 10 // ceil(StatisticalSecurityBits/8)

	// Collision resistance derived values
	CollisionResistanceBytesCeil = 32 // ceil(CollisionResistance/8)
)

// Compile-time assertions: 2^(ceil-1) < Bits ≤ 2^ceil
const (
	_ = uint(1) / uint((1<<ComputationalSecurityLog2Ceil)/ComputationalSecurityBits)
	_ = uint(1) / uint(ComputationalSecurityBits/(1<<(ComputationalSecurityLog2Ceil-1)))
)