// Code generated by bron-crypto. DO NOT EDIT.

package base

const (
	// ComputationalSecurity (λ) is the number of bits of computational security we want to achieve in most of our cryptographic primitives.
	ComputationalSecurityBits = 128
	ComputationalSecurityLog2Floor = 7
	ComputationalSecurityLog2Ceil  = 7
	ComputationalSecurityPow2Floor = 1 << ComputationalSecurityLog2Floor
	ComputationalSecurityPow2Ceil  = 1 << ComputationalSecurityLog2Ceil
	ComputationalSecurityBytesCeil = 16 // ceil(bits/8)

	// StatisticalSecurity (λ_s) is the number of bits of statistical security we want to achieve in most of our cryptographic primitives, applicable mostly to soundness of interactive proofs.
	StatisticalSecurityBits   = 80
	StatisticalSecurityBytesCeil = 10 // ceil(bits/8)

	// CollisionResistance is the hash digest length to achieve λ-bits of collision resistance (birthday paradox).
	CollisionResistance = 2 * ComputationalSecurityBits
	CollisionResistanceBytesCeil = 32

	// Hash-to-curve application tag
	Hash2CurveAppTag = "bron-crypto/hash2curve"
)

// Compile-time assertions: 2^(ceil-1) < Bits ≤ 2^ceil
const (
	_ = uint(1) / uint((1<<ComputationalSecurityLog2Ceil)/ComputationalSecurityBits)
	_ = uint(1) / uint(ComputationalSecurityBits/(1<<(ComputationalSecurityLog2Ceil-1)))
)