package testutils

import (
	"maps"
	"slices"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/bronlabs/bron-crypto/pkg/base"
	"github.com/bronlabs/bron-crypto/pkg/base/algebra"
	"github.com/bronlabs/bron-crypto/pkg/base/curves"
	ds "github.com/bronlabs/bron-crypto/pkg/base/datastructures"
	"github.com/bronlabs/bron-crypto/pkg/base/nt/num"
	"github.com/bronlabs/bron-crypto/pkg/base/prng/pcg"
	"github.com/bronlabs/bron-crypto/pkg/base/utils/sliceutils"
	"github.com/bronlabs/bron-crypto/pkg/mpc"
	"github.com/bronlabs/bron-crypto/pkg/mpc/dkg/trusteddealer"
	"github.com/bronlabs/bron-crypto/pkg/mpc/session"
	session_testutils "github.com/bronlabs/bron-crypto/pkg/mpc/session/testutils"
	"github.com/bronlabs/bron-crypto/pkg/mpc/sharing"
	"github.com/bronlabs/bron-crypto/pkg/mpc/sharing/accessstructures"
	"github.com/bronlabs/bron-crypto/pkg/mpc/sharing/vss/feldman"
	"github.com/bronlabs/bron-crypto/pkg/mpc/signatures/ecdsa/lindell17"
	"github.com/bronlabs/bron-crypto/pkg/mpc/signatures/ecdsa/lindell17/keygen/dkg"
	"github.com/bronlabs/bron-crypto/pkg/network"
	ntu "github.com/bronlabs/bron-crypto/pkg/network/testutils"
	"github.com/bronlabs/bron-crypto/pkg/proofs/sigma/compiler/fiatshamir"
	"github.com/bronlabs/bron-crypto/pkg/signatures/ecdsa"
)

const paillierKeyLen = 1024

// RunLindell17DKG runs the complete auxiliary-information DKG over base shards
// generated by the MSP trusted dealer and checks the resulting shard invariants.
func RunLindell17DKG[P curves.Point[P, B, S], B algebra.PrimeFieldElement[B], S algebra.PrimeFieldElement[S]](
	tb testing.TB,
	curve ecdsa.Curve[P, B, S],
	accessStructure accessstructures.Monotone,
) map[sharing.ID]*lindell17.Shard[P, B, S] {
	tb.Helper()

	prng := pcg.NewRandomised()
	quorum := accessStructure.Shareholders()
	baseShards, err := trusteddealer.Deal(curve, accessStructure, prng)
	require.NoError(tb, err)
	ctxs := session_testutils.MakeRandomContexts(tb, quorum, prng)

	participants := make(map[sharing.ID]*dkg.Participant[P, B, S], quorum.Size())
	for id := range quorum.Iter() {
		baseShard, ok := baseShards.Get(id)
		require.True(tb, ok)
		participants[id], err = dkg.NewParticipant(
			ctxs[id],
			baseShard,
			paillierKeyLen,
			curve,
			pcg.NewRandomised(),
			fiatshamir.Name,
		)
		require.NoError(tb, err)
	}
	participantsList := slices.Collect(maps.Values(participants))

	r1bo := make(map[sharing.ID]*dkg.Round1Broadcast[P, B, S], quorum.Size())
	for id, party := range participants {
		r1bo[id], err = party.Round1()
		require.NoError(tb, err)
	}

	r2bi := ntu.MapBroadcastO2I(tb, participantsList, r1bo)
	r2bo := make(map[sharing.ID]*dkg.Round2Broadcast[P, B, S], quorum.Size())
	for id, party := range participants {
		r2bo[id], err = party.Round2(r2bi[id])
		require.NoError(tb, err)
	}

	r3bi := ntu.MapBroadcastO2I(tb, participantsList, r2bo)
	r3bo := make(map[sharing.ID]*dkg.Round3Broadcast[P, B, S], quorum.Size())
	for id, party := range participants {
		r3bo[id], err = party.Round3(r3bi[id])
		require.NoError(tb, err)
	}

	r4bi := ntu.MapBroadcastO2I(tb, participantsList, r3bo)
	r4uo := make(map[sharing.ID]network.OutgoingUnicasts[*dkg.Round4P2P[P, B, S], *dkg.Participant[P, B, S]], quorum.Size())
	for id, party := range participants {
		r4uo[id], err = party.Round4(r4bi[id])
		require.NoError(tb, err)
	}

	r5ui := ntu.MapUnicastO2I(tb, participantsList, r4uo)
	r5uo := make(map[sharing.ID]network.OutgoingUnicasts[*dkg.Round5P2P[P, B, S], *dkg.Participant[P, B, S]], quorum.Size())
	for id, party := range participants {
		r5uo[id], err = party.Round5(r5ui[id])
		require.NoError(tb, err)
	}

	r6ui := ntu.MapUnicastO2I(tb, participantsList, r5uo)
	r6uo := make(map[sharing.ID]network.OutgoingUnicasts[*dkg.Round6P2P[P, B, S], *dkg.Participant[P, B, S]], quorum.Size())
	for id, party := range participants {
		r6uo[id], err = party.Round6(r6ui[id])
		require.NoError(tb, err)
	}

	r7ui := ntu.MapUnicastO2I(tb, participantsList, r6uo)
	r7uo := make(map[sharing.ID]network.OutgoingUnicasts[*dkg.Round7P2P[P, B, S], *dkg.Participant[P, B, S]], quorum.Size())
	for id, party := range participants {
		r7uo[id], err = party.Round7(r7ui[id])
		require.NoError(tb, err)
	}

	r8ui := ntu.MapUnicastO2I(tb, participantsList, r7uo)
	shards := make(map[sharing.ID]*lindell17.Shard[P, B, S], quorum.Size())
	for id, party := range participants {
		shards[id], err = party.Round8(r8ui[id])
		require.NoError(tb, err)
	}

	requireConsistentOutputs(tb, curve, accessStructure, baseShards, shards, ctxs)
	return shards
}

func requireConsistentOutputs[P curves.Point[P, B, S], B algebra.PrimeFieldElement[B], S algebra.PrimeFieldElement[S]](
	tb testing.TB,
	curve ecdsa.Curve[P, B, S],
	accessStructure accessstructures.Monotone,
	baseShards ds.Map[sharing.ID, *mpc.BaseShard[P, S]],
	shards map[sharing.ID]*lindell17.Shard[P, B, S],
	ctxs map[sharing.ID]*session.Context,
) {
	tb.Helper()

	quorum := accessStructure.Shareholders()
	ids := slices.Sorted(quorum.Iter())
	var transcriptReference []byte
	for _, id := range ids {
		transcriptData, err := ctxs[id].Transcript().ExtractBytes("test", base.ComputationalSecurityBytesCeil)
		require.NoError(tb, err)
		if transcriptReference == nil {
			transcriptReference = transcriptData
		} else {
			require.Equal(tb, transcriptReference, transcriptData)
		}

		baseShard, ok := baseShards.Get(id)
		require.True(tb, ok)
		require.True(tb, baseShard.Equal(&shards[id].BaseShard))
		require.NotNil(tb, shards[id].PaillierSecretKey())
		expectedPairCount := 0
		for peer := range quorum.Iter() {
			if peer != id && baseShard.MSP().Accepts(id, peer) {
				expectedPairCount++
			}
		}
		require.Equal(tb, expectedPairCount, shards[id].PaillierPublicKeys().Size())
		require.Equal(tb, expectedPairCount, shards[id].EncryptedShares().Size())
	}

	publicKey := shards[ids[0]].PublicKeyValue()
	q, err := num.Z().FromCardinal(curve.Order())
	require.NoError(tb, err)
	threeQ := q.Mul(num.Z().FromUint64(3))
	qSquared := q.Square()
	for _, id := range ids[1:] {
		require.True(tb, publicKey.Equal(shards[id].PublicKeyValue()))
	}

	for sender, senderShard := range shards {
		for observer, observerShard := range shards {
			if observer == sender || !accessStructure.IsQualified(sender, observer) {
				continue
			}
			ciphertexts, ok := observerShard.EncryptedShares().Get(sender)
			require.True(tb, ok)
			require.Len(tb, ciphertexts, len(senderShard.Share().Value()))
			for i, ciphertext := range ciphertexts {
				plaintext, err := senderShard.PaillierSecretKey().Decrypt(ciphertext)
				require.NoError(tb, err)
				require.True(tb, plaintext.Value().Lift().Compare(threeQ).IsLessThan(),
					"observer %d stored an encrypted lift >= 3q for sender %d component %d", observer, sender, i)
				actual, err := curve.ScalarField().FromBytesBEReduce(plaintext.Value().Big().Bytes())
				require.NoError(tb, err)
				require.True(tb, actual.Equal(senderShard.Share().Value()[i]),
					"observer %d stored the wrong encrypted raw MSP share for sender %d component %d", observer, sender, i)
			}
			peerPublicKey, ok := observerShard.PaillierPublicKeys().Get(sender)
			require.True(tb, ok)
			require.True(tb, peerPublicKey.Equal(senderShard.PaillierSecretKey().Public()))
			componentCount := num.Z().FromUint64(uint64(len(ciphertexts)))
			fullSigningBound := qSquared.Mul(q).
				Add(qSquared.Mul(num.Z().FromUint64(3)).Mul(componentCount)).
				Add(q.Mul(num.Z().FromUint64(2)))
			twiceFullSigningBound := fullSigningBound.Mul(num.Z().FromUint64(2))
			require.True(tb, twiceFullSigningBound.Compare(peerPublicKey.Group().N().Lift()).IsLessThan(),
				"Paillier modulus for sender %d is too small for the masked signing plaintext", sender)
		}
	}

	feldmanScheme, err := feldman.NewScheme(curve, accessStructure)
	require.NoError(tb, err)
	for size := uint(1); size <= uint(len(ids)); size++ {
		for subset := range sliceutils.Combinations(ids, size) {
			if !accessStructure.IsQualified(subset...) {
				continue
			}
			shares := make([]*feldman.Share[S], len(subset))
			for i, id := range subset {
				shares[i] = shards[id].Share()
			}
			recovered, err := feldmanScheme.Reconstruct(shares...)
			require.NoError(tb, err)
			require.True(tb, curve.ScalarBaseMul(recovered.Value()).Equal(publicKey))
		}
	}
}
