// Code generated by Fiat Cryptography. DO NOT EDIT.
//
// Autogenerated: '/usr/local/bin/fiat_crypto' unsaturated-solinas --lang Go --no-wide-int --relax-primitive-carry-to-bitwidth 32,64 --cmovznz-by-mul --internal-static --package-case flatcase --public-function-case UpperCamelCase --private-function-case camelCase --public-type-case UpperCamelCase --private-type-case camelCase --no-prefix-fiat --doc-newline-in-typedef-bounds --doc-prepend-header 'Code generated by Fiat Cryptography. DO NOT EDIT.' --doc-text-before-function-name '' --doc-text-before-type-name '' --package-name internal fp 64 '(auto)' '2^127 - 1'
//
// curve description: fp
//
// machine_wordsize = 64 (from "64")
//
// requested operations: (all)
//
// n = 3 (from "(auto)")
//
// s-c = 2^127 - [(1, 1)] (from "2^127 - 1")
//
// tight_bounds_multiplier = 1 (from "")
//
//
//
// Computed values:
//
//   carry_chain = [0, 1, 2, 0, 1]
//
//   eval z = z[0] + (z[1] << 43) + (z[2] << 85)
//
//   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120)
//
//   balance = [0xffffffffffe, 0x7fffffffffe, 0x7fffffffffe]
package internal

import "math/bits"

type fpUint1 uint64 // We use uint64 instead of a more narrow type for performance reasons; see https://github.com/mit-plv/fiat-crypto/pull/1006#issuecomment-892625927
type fpInt1 int64 // We use uint64 instead of a more narrow type for performance reasons; see https://github.com/mit-plv/fiat-crypto/pull/1006#issuecomment-892625927

// FpLooseFieldElement is a field element with loose bounds.
//
// Bounds:
//
//   [[0x0 ~> 0x180000000000], [0x0 ~> 0xc0000000000], [0x0 ~> 0xc0000000000]]
type FpLooseFieldElement [3]uint64

// FpTightFieldElement is a field element with tight bounds.
//
// Bounds:
//
//   [[0x0 ~> 0x80000000000], [0x0 ~> 0x40000000000], [0x0 ~> 0x40000000000]]
type FpTightFieldElement [3]uint64

// fpAddcarryxU42 is an addition with carry.
//
// Postconditions:
//   out1 = (arg1 + arg2 + arg3) mod 2^42
//   out2 = ⌊(arg1 + arg2 + arg3) / 2^42⌋
//
// Input Bounds:
//   arg1: [0x0 ~> 0x1]
//   arg2: [0x0 ~> 0x3ffffffffff]
//   arg3: [0x0 ~> 0x3ffffffffff]
// Output Bounds:
//   out1: [0x0 ~> 0x3ffffffffff]
//   out2: [0x0 ~> 0x1]
func fpAddcarryxU42(out1 *uint64, out2 *fpUint1, arg1 fpUint1, arg2 uint64, arg3 uint64) {
	x1 := ((uint64(arg1) + arg2) + arg3)
	x2 := (x1 & 0x3ffffffffff)
	x3 := fpUint1((x1 >> 42))
	*out1 = x2
	*out2 = x3
}

// fpSubborrowxU42 is a subtraction with borrow.
//
// Postconditions:
//   out1 = (-arg1 + arg2 + -arg3) mod 2^42
//   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^42⌋
//
// Input Bounds:
//   arg1: [0x0 ~> 0x1]
//   arg2: [0x0 ~> 0x3ffffffffff]
//   arg3: [0x0 ~> 0x3ffffffffff]
// Output Bounds:
//   out1: [0x0 ~> 0x3ffffffffff]
//   out2: [0x0 ~> 0x1]
func fpSubborrowxU42(out1 *uint64, out2 *fpUint1, arg1 fpUint1, arg2 uint64, arg3 uint64) {
	x1 := ((int64(arg2) - int64(arg1)) - int64(arg3))
	x2 := fpInt1((x1 >> 42))
	x3 := (uint64(x1) & 0x3ffffffffff)
	*out1 = x3
	*out2 = (0x0 - fpUint1(x2))
}

// fpAddcarryxU43 is an addition with carry.
//
// Postconditions:
//   out1 = (arg1 + arg2 + arg3) mod 2^43
//   out2 = ⌊(arg1 + arg2 + arg3) / 2^43⌋
//
// Input Bounds:
//   arg1: [0x0 ~> 0x1]
//   arg2: [0x0 ~> 0x7ffffffffff]
//   arg3: [0x0 ~> 0x7ffffffffff]
// Output Bounds:
//   out1: [0x0 ~> 0x7ffffffffff]
//   out2: [0x0 ~> 0x1]
func fpAddcarryxU43(out1 *uint64, out2 *fpUint1, arg1 fpUint1, arg2 uint64, arg3 uint64) {
	x1 := ((uint64(arg1) + arg2) + arg3)
	x2 := (x1 & 0x7ffffffffff)
	x3 := fpUint1((x1 >> 43))
	*out1 = x2
	*out2 = x3
}

// fpSubborrowxU43 is a subtraction with borrow.
//
// Postconditions:
//   out1 = (-arg1 + arg2 + -arg3) mod 2^43
//   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^43⌋
//
// Input Bounds:
//   arg1: [0x0 ~> 0x1]
//   arg2: [0x0 ~> 0x7ffffffffff]
//   arg3: [0x0 ~> 0x7ffffffffff]
// Output Bounds:
//   out1: [0x0 ~> 0x7ffffffffff]
//   out2: [0x0 ~> 0x1]
func fpSubborrowxU43(out1 *uint64, out2 *fpUint1, arg1 fpUint1, arg2 uint64, arg3 uint64) {
	x1 := ((int64(arg2) - int64(arg1)) - int64(arg3))
	x2 := fpInt1((x1 >> 43))
	x3 := (uint64(x1) & 0x7ffffffffff)
	*out1 = x3
	*out2 = (0x0 - fpUint1(x2))
}

// fpCmovznzU64 is a single-word conditional move.
//
// Postconditions:
//   out1 = (if arg1 = 0 then arg2 else arg3)
//
// Input Bounds:
//   arg1: [0x0 ~> 0x1]
//   arg2: [0x0 ~> 0xffffffffffffffff]
//   arg3: [0x0 ~> 0xffffffffffffffff]
// Output Bounds:
//   out1: [0x0 ~> 0xffffffffffffffff]
func fpCmovznzU64(out1 *uint64, arg1 fpUint1, arg2 uint64, arg3 uint64) {
	x1 := (uint64(arg1) * 0xffffffffffffffff)
	x2 := ((x1 & arg3) | ((^x1) & arg2))
	*out1 = x2
}

// FpCarryMul multiplies two field elements and reduces the result.
//
// Postconditions:
//   eval out1 mod m = (eval arg1 * eval arg2) mod m
//
func FpCarryMul(out1 *FpTightFieldElement, arg1 *FpLooseFieldElement, arg2 *FpLooseFieldElement) {
	var x1 uint64
	var x2 uint64
	x2, x1 = bits.Mul64(arg1[2], arg2[2])
	var x3 uint64
	var x4 uint64
	x4, x3 = bits.Mul64(arg1[2], (arg2[1] * 0x2))
	var x5 uint64
	var x6 uint64
	x6, x5 = bits.Mul64(arg1[1], (arg2[2] * 0x2))
	var x7 uint64
	var x8 uint64
	x8, x7 = bits.Mul64(arg1[2], arg2[0])
	var x9 uint64
	var x10 uint64
	x10, x9 = bits.Mul64(arg1[1], (arg2[1] * 0x2))
	var x11 uint64
	var x12 uint64
	x12, x11 = bits.Mul64(arg1[1], arg2[0])
	var x13 uint64
	var x14 uint64
	x14, x13 = bits.Mul64(arg1[0], arg2[2])
	var x15 uint64
	var x16 uint64
	x16, x15 = bits.Mul64(arg1[0], arg2[1])
	var x17 uint64
	var x18 uint64
	x18, x17 = bits.Mul64(arg1[0], arg2[0])
	var x19 uint64
	var x20 uint64
	x19, x20 = bits.Add64(x5, x3, uint64(0x0))
	var x21 uint64
	x21, _ = bits.Add64(x6, x4, uint64(fpUint1(x20)))
	var x23 uint64
	var x24 uint64
	x23, x24 = bits.Add64(x17, x19, uint64(0x0))
	var x25 uint64
	x25, _ = bits.Add64(x18, x21, uint64(fpUint1(x24)))
	x27 := ((x23 >> 43) | ((x25 << 21) & 0xffffffffffffffff))
	x28 := (x23 & 0x7ffffffffff)
	var x29 uint64
	var x30 uint64
	x29, x30 = bits.Add64(x9, x7, uint64(0x0))
	var x31 uint64
	x31, _ = bits.Add64(x10, x8, uint64(fpUint1(x30)))
	var x33 uint64
	var x34 uint64
	x33, x34 = bits.Add64(x13, x29, uint64(0x0))
	var x35 uint64
	x35, _ = bits.Add64(x14, x31, uint64(fpUint1(x34)))
	var x37 uint64
	var x38 uint64
	x37, x38 = bits.Add64(x11, x1, uint64(0x0))
	var x39 uint64
	x39, _ = bits.Add64(x12, x2, uint64(fpUint1(x38)))
	var x41 uint64
	var x42 uint64
	x41, x42 = bits.Add64(x15, x37, uint64(0x0))
	var x43 uint64
	x43, _ = bits.Add64(x16, x39, uint64(fpUint1(x42)))
	var x45 uint64
	var x46 uint64
	x45, x46 = bits.Add64(x27, x41, uint64(0x0))
	x47 := (uint64(fpUint1(x46)) + x43)
	x48 := ((x45 >> 42) | ((x47 << 22) & 0xffffffffffffffff))
	x49 := (x45 & 0x3ffffffffff)
	var x50 uint64
	var x51 uint64
	x50, x51 = bits.Add64(x48, x33, uint64(0x0))
	x52 := (uint64(fpUint1(x51)) + x35)
	x53 := ((x50 >> 42) | ((x52 << 22) & 0xffffffffffffffff))
	x54 := (x50 & 0x3ffffffffff)
	x55 := (x28 + x53)
	x56 := (x55 >> 43)
	x57 := (x55 & 0x7ffffffffff)
	x58 := (x56 + x49)
	x59 := fpUint1((x58 >> 42))
	x60 := (x58 & 0x3ffffffffff)
	x61 := (uint64(x59) + x54)
	out1[0] = x57
	out1[1] = x60
	out1[2] = x61
}

// FpCarrySquare squares a field element and reduces the result.
//
// Postconditions:
//   eval out1 mod m = (eval arg1 * eval arg1) mod m
//
func FpCarrySquare(out1 *FpTightFieldElement, arg1 *FpLooseFieldElement) {
	x1 := arg1[2]
	x2 := (x1 * 0x2)
	x3 := (arg1[2] * 0x2)
	x4 := (arg1[1] * 0x2)
	var x5 uint64
	var x6 uint64
	x6, x5 = bits.Mul64(arg1[2], x1)
	var x7 uint64
	var x8 uint64
	x8, x7 = bits.Mul64(arg1[1], (x2 * 0x2))
	var x9 uint64
	var x10 uint64
	x10, x9 = bits.Mul64(arg1[1], (arg1[1] * 0x2))
	var x11 uint64
	var x12 uint64
	x12, x11 = bits.Mul64(arg1[0], x3)
	var x13 uint64
	var x14 uint64
	x14, x13 = bits.Mul64(arg1[0], x4)
	var x15 uint64
	var x16 uint64
	x16, x15 = bits.Mul64(arg1[0], arg1[0])
	var x17 uint64
	var x18 uint64
	x17, x18 = bits.Add64(x15, x7, uint64(0x0))
	var x19 uint64
	x19, _ = bits.Add64(x16, x8, uint64(fpUint1(x18)))
	x21 := ((x17 >> 43) | ((x19 << 21) & 0xffffffffffffffff))
	x22 := (x17 & 0x7ffffffffff)
	var x23 uint64
	var x24 uint64
	x23, x24 = bits.Add64(x11, x9, uint64(0x0))
	var x25 uint64
	x25, _ = bits.Add64(x12, x10, uint64(fpUint1(x24)))
	var x27 uint64
	var x28 uint64
	x27, x28 = bits.Add64(x13, x5, uint64(0x0))
	var x29 uint64
	x29, _ = bits.Add64(x14, x6, uint64(fpUint1(x28)))
	var x31 uint64
	var x32 uint64
	x31, x32 = bits.Add64(x21, x27, uint64(0x0))
	x33 := (uint64(fpUint1(x32)) + x29)
	x34 := ((x31 >> 42) | ((x33 << 22) & 0xffffffffffffffff))
	x35 := (x31 & 0x3ffffffffff)
	var x36 uint64
	var x37 uint64
	x36, x37 = bits.Add64(x34, x23, uint64(0x0))
	x38 := (uint64(fpUint1(x37)) + x25)
	x39 := ((x36 >> 42) | ((x38 << 22) & 0xffffffffffffffff))
	x40 := (x36 & 0x3ffffffffff)
	x41 := (x22 + x39)
	x42 := (x41 >> 43)
	x43 := (x41 & 0x7ffffffffff)
	x44 := (x42 + x35)
	x45 := fpUint1((x44 >> 42))
	x46 := (x44 & 0x3ffffffffff)
	x47 := (uint64(x45) + x40)
	out1[0] = x43
	out1[1] = x46
	out1[2] = x47
}

// FpCarry reduces a field element.
//
// Postconditions:
//   eval out1 mod m = eval arg1 mod m
//
func FpCarry(out1 *FpTightFieldElement, arg1 *FpLooseFieldElement) {
	x1 := arg1[0]
	x2 := ((x1 >> 43) + arg1[1])
	x3 := ((x2 >> 42) + arg1[2])
	x4 := ((x1 & 0x7ffffffffff) + (x3 >> 42))
	x5 := (uint64(fpUint1((x4 >> 43))) + (x2 & 0x3ffffffffff))
	x6 := (x4 & 0x7ffffffffff)
	x7 := (x5 & 0x3ffffffffff)
	x8 := (uint64(fpUint1((x5 >> 42))) + (x3 & 0x3ffffffffff))
	out1[0] = x6
	out1[1] = x7
	out1[2] = x8
}

// FpAdd adds two field elements.
//
// Postconditions:
//   eval out1 mod m = (eval arg1 + eval arg2) mod m
//
func FpAdd(out1 *FpLooseFieldElement, arg1 *FpTightFieldElement, arg2 *FpTightFieldElement) {
	x1 := (arg1[0] + arg2[0])
	x2 := (arg1[1] + arg2[1])
	x3 := (arg1[2] + arg2[2])
	out1[0] = x1
	out1[1] = x2
	out1[2] = x3
}

// FpSub subtracts two field elements.
//
// Postconditions:
//   eval out1 mod m = (eval arg1 - eval arg2) mod m
//
func FpSub(out1 *FpLooseFieldElement, arg1 *FpTightFieldElement, arg2 *FpTightFieldElement) {
	x1 := ((0xffffffffffe + arg1[0]) - arg2[0])
	x2 := ((0x7fffffffffe + arg1[1]) - arg2[1])
	x3 := ((0x7fffffffffe + arg1[2]) - arg2[2])
	out1[0] = x1
	out1[1] = x2
	out1[2] = x3
}

// FpOpp negates a field element.
//
// Postconditions:
//   eval out1 mod m = -eval arg1 mod m
//
func FpOpp(out1 *FpLooseFieldElement, arg1 *FpTightFieldElement) {
	x1 := (0xffffffffffe - arg1[0])
	x2 := (0x7fffffffffe - arg1[1])
	x3 := (0x7fffffffffe - arg1[2])
	out1[0] = x1
	out1[1] = x2
	out1[2] = x3
}

// FpCarryAdd adds two field elements.
//
// Postconditions:
//   eval out1 mod m = (eval arg1 + eval arg2) mod m
//
func FpCarryAdd(out1 *FpTightFieldElement, arg1 *FpTightFieldElement, arg2 *FpTightFieldElement) {
	x1 := (arg1[0] + arg2[0])
	x2 := ((x1 >> 43) + (arg1[1] + arg2[1]))
	x3 := ((x2 >> 42) + (arg1[2] + arg2[2]))
	x4 := ((x1 & 0x7ffffffffff) + (x3 >> 42))
	x5 := (uint64(fpUint1((x4 >> 43))) + (x2 & 0x3ffffffffff))
	x6 := (x4 & 0x7ffffffffff)
	x7 := (x5 & 0x3ffffffffff)
	x8 := (uint64(fpUint1((x5 >> 42))) + (x3 & 0x3ffffffffff))
	out1[0] = x6
	out1[1] = x7
	out1[2] = x8
}

// FpCarrySub subtracts two field elements.
//
// Postconditions:
//   eval out1 mod m = (eval arg1 - eval arg2) mod m
//
func FpCarrySub(out1 *FpTightFieldElement, arg1 *FpTightFieldElement, arg2 *FpTightFieldElement) {
	x1 := ((0xffffffffffe + arg1[0]) - arg2[0])
	x2 := ((x1 >> 43) + ((0x7fffffffffe + arg1[1]) - arg2[1]))
	x3 := ((x2 >> 42) + ((0x7fffffffffe + arg1[2]) - arg2[2]))
	x4 := ((x1 & 0x7ffffffffff) + (x3 >> 42))
	x5 := (uint64(fpUint1((x4 >> 43))) + (x2 & 0x3ffffffffff))
	x6 := (x4 & 0x7ffffffffff)
	x7 := (x5 & 0x3ffffffffff)
	x8 := (uint64(fpUint1((x5 >> 42))) + (x3 & 0x3ffffffffff))
	out1[0] = x6
	out1[1] = x7
	out1[2] = x8
}

// FpCarryOpp negates a field element.
//
// Postconditions:
//   eval out1 mod m = -eval arg1 mod m
//
func FpCarryOpp(out1 *FpTightFieldElement, arg1 *FpTightFieldElement) {
	x1 := (0xffffffffffe - arg1[0])
	x2 := (uint64(fpUint1((x1 >> 43))) + (0x7fffffffffe - arg1[1]))
	x3 := (uint64(fpUint1((x2 >> 42))) + (0x7fffffffffe - arg1[2]))
	x4 := ((x1 & 0x7ffffffffff) + uint64(fpUint1((x3 >> 42))))
	x5 := (uint64(fpUint1((x4 >> 43))) + (x2 & 0x3ffffffffff))
	x6 := (x4 & 0x7ffffffffff)
	x7 := (x5 & 0x3ffffffffff)
	x8 := (uint64(fpUint1((x5 >> 42))) + (x3 & 0x3ffffffffff))
	out1[0] = x6
	out1[1] = x7
	out1[2] = x8
}

// FpRelax is the identity function converting from tight field elements to loose field elements.
//
// Postconditions:
//   out1 = arg1
//
func FpRelax(out1 *FpLooseFieldElement, arg1 *FpTightFieldElement) {
	x1 := arg1[0]
	x2 := arg1[1]
	x3 := arg1[2]
	out1[0] = x1
	out1[1] = x2
	out1[2] = x3
}

// FpSelectznz is a multi-limb conditional select.
//
// Postconditions:
//   out1 = (if arg1 = 0 then arg2 else arg3)
//
// Input Bounds:
//   arg1: [0x0 ~> 0x1]
//   arg2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
//   arg3: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
// Output Bounds:
//   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
func FpSelectznz(out1 *[3]uint64, arg1 fpUint1, arg2 *[3]uint64, arg3 *[3]uint64) {
	var x1 uint64
	fpCmovznzU64(&x1, arg1, arg2[0], arg3[0])
	var x2 uint64
	fpCmovznzU64(&x2, arg1, arg2[1], arg3[1])
	var x3 uint64
	fpCmovznzU64(&x3, arg1, arg2[2], arg3[2])
	out1[0] = x1
	out1[1] = x2
	out1[2] = x3
}

// FpToBytes serializes a field element to bytes in little-endian order.
//
// Postconditions:
//   out1 = map (λ x, ⌊((eval arg1 mod m) mod 2^(8 * (x + 1))) / 2^(8 * x)⌋) [0..15]
//
// Output Bounds:
//   out1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x7f]]
func FpToBytes(out1 *[16]uint8, arg1 *FpTightFieldElement) {
	var x1 uint64
	var x2 fpUint1
	fpSubborrowxU43(&x1, &x2, 0x0, arg1[0], 0x7ffffffffff)
	var x3 uint64
	var x4 fpUint1
	fpSubborrowxU42(&x3, &x4, x2, arg1[1], 0x3ffffffffff)
	var x5 uint64
	var x6 fpUint1
	fpSubborrowxU42(&x5, &x6, x4, arg1[2], 0x3ffffffffff)
	var x7 uint64
	fpCmovznzU64(&x7, x6, uint64(0x0), 0xffffffffffffffff)
	var x8 uint64
	var x9 fpUint1
	fpAddcarryxU43(&x8, &x9, 0x0, x1, (x7 & 0x7ffffffffff))
	var x10 uint64
	var x11 fpUint1
	fpAddcarryxU42(&x10, &x11, x9, x3, (x7 & 0x3ffffffffff))
	var x12 uint64
	var x13 fpUint1
	fpAddcarryxU42(&x12, &x13, x11, x5, (x7 & 0x3ffffffffff))
	x14 := (x12 << 5)
	x15 := (x10 << 3)
	x16 := (uint8(x8) & 0xff)
	x17 := (x8 >> 8)
	x18 := (uint8(x17) & 0xff)
	x19 := (x17 >> 8)
	x20 := (uint8(x19) & 0xff)
	x21 := (x19 >> 8)
	x22 := (uint8(x21) & 0xff)
	x23 := (x21 >> 8)
	x24 := (uint8(x23) & 0xff)
	x25 := uint8((x23 >> 8))
	x26 := (x15 + uint64(x25))
	x27 := (uint8(x26) & 0xff)
	x28 := (x26 >> 8)
	x29 := (uint8(x28) & 0xff)
	x30 := (x28 >> 8)
	x31 := (uint8(x30) & 0xff)
	x32 := (x30 >> 8)
	x33 := (uint8(x32) & 0xff)
	x34 := (x32 >> 8)
	x35 := (uint8(x34) & 0xff)
	x36 := uint8((x34 >> 8))
	x37 := (x14 + uint64(x36))
	x38 := (uint8(x37) & 0xff)
	x39 := (x37 >> 8)
	x40 := (uint8(x39) & 0xff)
	x41 := (x39 >> 8)
	x42 := (uint8(x41) & 0xff)
	x43 := (x41 >> 8)
	x44 := (uint8(x43) & 0xff)
	x45 := (x43 >> 8)
	x46 := (uint8(x45) & 0xff)
	x47 := uint8((x45 >> 8))
	out1[0] = x16
	out1[1] = x18
	out1[2] = x20
	out1[3] = x22
	out1[4] = x24
	out1[5] = x27
	out1[6] = x29
	out1[7] = x31
	out1[8] = x33
	out1[9] = x35
	out1[10] = x38
	out1[11] = x40
	out1[12] = x42
	out1[13] = x44
	out1[14] = x46
	out1[15] = x47
}

// FpFromBytes deserializes a field element from bytes in little-endian order.
//
// Postconditions:
//   eval out1 mod m = bytes_eval arg1 mod m
//
// Input Bounds:
//   arg1: [[0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0xff], [0x0 ~> 0x7f]]
func FpFromBytes(out1 *FpTightFieldElement, arg1 *[16]uint8) {
	x1 := (uint64(arg1[15]) << 35)
	x2 := (uint64(arg1[14]) << 27)
	x3 := (uint64(arg1[13]) << 19)
	x4 := (uint64(arg1[12]) << 11)
	x5 := (uint64(arg1[11]) << 3)
	x6 := (uint64(arg1[10]) << 37)
	x7 := (uint64(arg1[9]) << 29)
	x8 := (uint64(arg1[8]) << 21)
	x9 := (uint64(arg1[7]) << 13)
	x10 := (uint64(arg1[6]) << 5)
	x11 := (uint64(arg1[5]) << 40)
	x12 := (uint64(arg1[4]) << 32)
	x13 := (uint64(arg1[3]) << 24)
	x14 := (uint64(arg1[2]) << 16)
	x15 := (uint64(arg1[1]) << 8)
	x16 := arg1[0]
	x17 := (x15 + uint64(x16))
	x18 := (x14 + x17)
	x19 := (x13 + x18)
	x20 := (x12 + x19)
	x21 := (x11 + x20)
	x22 := (x21 & 0x7ffffffffff)
	x23 := uint8((x21 >> 43))
	x24 := (x10 + uint64(x23))
	x25 := (x9 + x24)
	x26 := (x8 + x25)
	x27 := (x7 + x26)
	x28 := (x6 + x27)
	x29 := (x28 & 0x3ffffffffff)
	x30 := uint8((x28 >> 42))
	x31 := (x5 + uint64(x30))
	x32 := (x4 + x31)
	x33 := (x3 + x32)
	x34 := (x2 + x33)
	x35 := (x1 + x34)
	out1[0] = x22
	out1[1] = x29
	out1[2] = x35
}
