package curves

import (
	"github.com/cronokirby/saferith"
)

// Curve represents a named elliptic curve with a scalar field and point group.
type Curve interface {
	// CurveProfile returns the profile of the curve (field, subgroup order, cofactor, etc.).
	Profile() CurveProfile
	// Scalar exposes the scalar field interface of this curve.
	Scalar() Scalar
	// Point exposes the point group interface of this curve.
	Point() Point

	// Name returns the name of the curve.
	Name() string
	// Generator returns the generator point G of the curve.
	Generator() Point
	// ScalarBaseMult yields the scalar multiplication of `sc * Generator`.
	ScalarBaseMult(sc Scalar) Point
	// MultiScalarMult yields the sum `Σ_i (scalars[i] * points[i])`
	MultiScalarMult(scalars []Scalar, points []Point) (Point, error)
	// DeriveFromAffineX returns the two points on the curve with the given x-coordinate.
	DeriveFromAffineX(x FieldElement) (evenY, oddY Point, err error)
}

type PairingCurve interface {
	PairingCurveProfile() PairingCurveProfile
	Name() string

	// G1
	// Yes. These are not curves, but the API is nice and gives us access to the base fields and scalar fields etc.
	G1() Curve
	PointG1() PairingPoint
	G2() Curve
	PointG2() PairingPoint
	Gt() Scalar

	Pairing(pG1, pG2 PairingPoint) Scalar
	MultiPairing(...PairingPoint) Scalar
}

type WeierstrassCurve interface {
	Curve
	WeierstrassPoint
}

type CurveProfile interface {
	// Field returns the finite field profile over which the curve is defined
	Field() FieldProfile
	// SubGroupOrder returns the order of the subgroup generated by G
	SubGroupOrder() *saferith.Modulus
	// Cofactor return cofactor defined as Ord(Fp) / Ord(G)
	Cofactor() Scalar
	// ToPairingCurve returns the larger PairingCurve interface, or nil if the curve is not pairing friendly.
	ToPairingCurve() PairingCurve
}

type PairingCurveProfile interface {
	EmbeddingDegree() *saferith.Nat
}
