#!/bin/bash
dockerfile=$(mktemp)
cat << EOF > "${dockerfile}"
  FROM alpine:3.21.2
  RUN wget https://github.com/mit-plv/fiat-crypto/releases/download/v0.1.4/Fiat-Cryptography_v0.1.4_Linux_x86_64 -O /usr/local/bin/fiatcrypto && \
      chmod +x /usr/local/bin/fiatcrypto

  CMD ["/usr/local/bin/fiatcrypto"]
EOF
output="${GOFILE%.go}.gen.go"
image=$(docker build -q --platform=linux/amd64 -f "${dockerfile}" .)
docker run --rm "${image}" fiatcrypto word-by-word-montgomery --lang Go --no-wide-int --relax-primitive-carry-to-bitwidth 32,64 --cmovznz-by-mul --internal-static --package-case flatcase --public-function-case UpperCamelCase --private-function-case camelCase --public-type-case UpperCamelCase --private-type-case camelCase --no-prefix-fiat --doc-newline-in-typedef-bounds --doc-prepend-header 'Code generated by Fiat Cryptography. DO NOT EDIT.' --doc-text-before-function-name '' --doc-text-before-type-name '' --package-name "${GOPACKAGE}" "$@" > "${output}"
rm "${dockerfile}"
