package softspoken

import (
	"github.com/copperexchange/crypto-primitives-go/pkg/core/curves"
	"github.com/copperexchange/crypto-primitives-go/pkg/ot/base/simplest"
)

const (
	// ------------------------ CONFIGURABLE PARAMETERS --------------------- //
	// Kappa (κ) is the computational security parameter. Set |q| = κ for a curve
	// of prime order q. This is the size of the PRG seeds (the BaseOT options)
	// as well as the number of BaseOT elements per "block" of OTextension.
	Kappa = 256

	// extensionFactor is the ratio between scalars generated by the OTextension
	// and the BaseOT scalars used as seeds.
	extensionFactor = 2

	// S is the statistical security parameter. Must divide L (L%S=0) for SoftSpokenOT.
	//  This defines the data type of the consistency check to 2^S bits (e.g. S=128 -> Uint128)
	S = 128

	// ---------------------- NON-CONFIGURABLE PARAMETERS ------------------- //
	// KeyCount is the number of scalars to choose from in the BaseOT, as well as
	//  the number of shares _per_ choice of the cOT. Set to 2 for 1-out-of-2 OT
	//  and one share per party.
	KeyCount = 2

	// L is the batch size in bits used in the cOT functionality.
	L = extensionFactor * Kappa

	// length of pseudorandom seed expansion
	LPrime = L + S

	// number of blocks in the consistency check
	M = L / S

	// Equivalents in Bytes
	KappaBytes  = Kappa >> 3
	LBytes      = L >> 3
	SBytes      = S >> 3
	LPrimeBytes = LPrime >> 3
	MBytes      = M >> 3
)

type Receiver struct {
	// baseOtSendOptions (k^i_0, k^i_1) ∈ [2][κ][κ]bits are the options used while
	//  of playing the sender in a base OT protocol. They are inputs to COTe.
	baseOtSendOptions *simplest.SenderOutput

	// ExtPackChoices (x_i) ∈ [L']bits are the choice bits for the OTe.
	ExtPackChoices [LPrimeBytes]byte

	// ExtOptions (t^i) ∈ [2][κ][L']bits are expansions of BaseOT results using a PRG.
	ExtOptions [KeyCount][Kappa][LPrimeBytes]byte

	// TRExtChosenOpt (v_x) ∈ [L][κ]bits are the transposed and randomized chosenOptions
	TRExtChosenOpt [L][KappaBytes]byte

	// OutCorrelations (z_B) ∈ [L]curve.Scalar are the output "correlations" (in the curve).
	OutCorrelations [L]curves.Scalar

	curve           *curves.Curve
	forcedReuse     bool
	uniqueSessionId [simplest.DigestSize]byte // store this between rounds
}

type Sender struct {
	// baseOtRecOutputs (Δ_i ∈ [κ]bits, k^i_{Δ_i} ∈ [κ][κ]bits) are the results
	// of playing the receiver in a base OT protocol. They are inputs of COTe.
	baseOtRecOutputs *simplest.ReceiverOutput

	// ExtChosenOpt (t^i_{Δ_i}) ∈ [κ][L']bits are the expanded (via a PRG) baseOT chosenOption
	ExtChosenOpt [Kappa][LPrimeBytes]byte

	// ExtCorrelations (q_i) ∈ [κ][L']bits are the extended correlations, such that:
	//    q^i = Δ_i • x + t^i
	ExtCorrelations [Kappa][LPrimeBytes]byte

	// TRExtOpts (v_{0,j} and v_{1,j}) ∈ [2][L][κ]bits are the transposed & randomized protocols
	TRExtOpts [2][L][KappaBytes]byte

	// OutDeltaOpt (z_A) ∈ [L]curve.Scalar are the output "ChosenOpt" group elements.
	OutDeltaOpt [L]curves.Scalar

	// curve is the elliptic curve used in the protocol.
	curve       *curves.Curve
	forcedReuse bool
}

// NewCOtReceiver creates a `Receiver` instance for the SoftSpokenOT protocol.
// The `baseOtResults` are the results of playing the sender role in kappa baseOTs.
func NewCOtReceiver(baseOtResults *simplest.SenderOutput, curve *curves.Curve, forcedReuse bool) *Receiver {
	return &Receiver{
		forcedReuse:       forcedReuse,
		baseOtSendOptions: baseOtResults,
		curve:             curve,
	}
}

// NewCOtSender creates a `Sender` instance for the SoftSpokenOT protocol.
// The `baseOtResults` are the results of playing the receiver role in kappa baseOTs.
func NewCOtSender(baseOtResults *simplest.ReceiverOutput, curve *curves.Curve, forcedReuse bool) *Sender {
	return &Sender{
		forcedReuse:      forcedReuse,
		baseOtRecOutputs: baseOtResults,
		curve:            curve,
	}
}
