package main

import (
	"context"
	_ "embed"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"os"
	"path/filepath"
)

//go:embed fiat-crypto.Dockerfile
var fiatCryptoDockerfileString string

func GenerateFiat(goPackage, goType, modulus string) (fiatFileName string) {
	fiatFileName = FiatFilePrefix + cases.Lower(language.English).String(goType) + GenGoExt
	outFile := Must(os.Create(fiatFileName))
	defer outFile.Close()

	dockerFileDir := Must(os.MkdirTemp("", "codegen"))
	dockerFile := Must(os.CreateTemp(dockerFileDir, "*.Dockerfile"))
	Must(dockerFile.WriteString(fiatCryptoDockerfileString))
	Must0(dockerFile.Close())

	fiatContainerRequest := testcontainers.ContainerRequest{
		FromDockerfile: testcontainers.FromDockerfile{
			Context:    dockerFileDir,
			Dockerfile: filepath.Base(dockerFile.Name()),
		},
		Cmd: []string{
			"word-by-word-montgomery",
			"--lang", "Go",
			"--no-wide-int",
			"--relax-primitive-carry-to-bitwidth", "32,64",
			"--cmovznz-by-mul",
			"--internal-static",
			"--package-case", "flatcase",
			"--public-function-case", "camelCase",
			"--private-function-case", "camelCase",
			"--public-type-case", "camelCase",
			"--private-type-case", "camelCase",
			"--doc-newline-in-typedef-bounds",
			"--doc-prepend-header", "Code generated by Fiat Cryptography. DO NOT EDIT.",
			"--doc-text-before-function-name", "",
			"--doc-text-before-type-name", "",
			"--package-name", goPackage,
			goType, "64", modulus,
		},
		LogConsumerCfg: &testcontainers.LogConsumerConfig{
			Consumers: []testcontainers.LogConsumer{NewWriterLogConsumer(outFile)},
		},
		WaitingFor: wait.ForExit(),
	}

	fiatContainer := Must(testcontainers.GenericContainer(context.Background(), testcontainers.GenericContainerRequest{
		ContainerRequest: fiatContainerRequest,
		Started:          true,
	}))
	defer fiatContainer.Terminate(context.Background())

	return outFile.Name()
}

func FindLimbCount(pkgName, fiatFileName, fiatElementTypeName string) uint64 {
	fiatFileSet := token.NewFileSet()
	fiatFileAst := Must(parser.ParseFile(fiatFileSet, fiatFileName, nil, parser.AllErrors))

	conf := types.Config{Importer: importer.Default()}
	pkg := Must(conf.Check(pkgName, fiatFileSet, []*ast.File{fiatFileAst}, nil))
	fiatElementObj := pkg.Scope().Lookup(fiatElementTypeName)
	if fiatElementObj == nil {
		panic("could not find MontgomeryDomainFieldElement")
	}

	fiatElementArray, ok := fiatElementObj.Type().Underlying().(*types.Array)
	if !ok {
		panic("MontgomeryDomainFieldElement is not an array")
	}

	return uint64(fiatElementArray.Len())
}
